### ISSUE TITLE
leading slash was added/displayed to the beginning of the field of IPv4 date type

### ISSUE THREAD

**Issue by patrickdung** [ClickHouse/clickhouse-java#1307]
### Describe the bug

Backend is Clickhouse
Using helm chart

```
customConfig:
  data_dir: /vector-data-dir
  api:
    enabled: true
    address: 127.0.0.1:8686
    playground: false
  sources:
    source_k8s_logs:
      type: kubernetes_logs
      pod_annotation_fields:
        pod_ip: kubernetes_pod_ip
        pod_ips: kubernetes_pod_ips
        pod_name: kubernetes_pod_name
        pod_namespace: kubernetes_pod_namespace
        pod_node_name: kubernetes_pod_node_name
 sinks:
   vector_to_clickhouse:
      type: clickhouse
      inputs:
        - source_k8s_logs
      endpoint: http://ch1.ch.svc.cluster.local:8123
      healthcheck:
        enabled: false
      database: logdb
      table: vector_k8s_logs_v2
      auth:
        strategy: basic
        user: logdb
        password: removed
      skip_unknown_fields: true
      buffer:
        max_events: 5000
      batch:
        timeout_secs: 40
      encoding:
        timestamp_format: rfc3339
```

Here's CH schema
```
CREATE TABLE IF NOT EXISTS
  logdb.vector_k8s_logs
(
   `timestamp` String,
   `parsed_timestamp` DateTime64(9) DEFAULT
      parseDateTime64BestEffort(timestamp, 9) CODEC(Delta(2), ZSTD(1)),
   `file` String,
   `kubernetes_pod_ip` IPv4,
   `kubernetes_pod_ips` Array(IPv4),
   `kubernetes_pod_labels` Map(LowCardinality(String), String),
   `kubernetes_pod_name` LowCardinality(String),
   `kubernetes_pod_namespace` LowCardinality(String),
   `kubernetes_pod_node_name` LowCardinality(String),
   `message` String,
   `source_type` LowCardinality(String),
   `stream` Enum('stdout', 'stderr')
)
ENGINE MergeTree
PARTITION BY toDate(parsed_timestamp)
ORDER BY parsed_timestamp;
```

The record should be fine when I use CH cli to view it.
When I use DBeaver via JDBC http, for kubernetes_pod_ip and kubernetes_pod_ips, there is a leading slash.
![image](https://user-images.githubusercontent.com/38665827/229797951-638fabf8-0838-4e8b-8e76-5a48b56630a5.png)

If I use SQLworkBench, the leading slash exists for kubernetes_pod_ips (Array of IPv4)..
![image](https://user-images.githubusercontent.com/38665827/229798155-c9fe028f-211d-440c-8ddc-f70ccc5478fd.png)

For CH, if I use String data type instead of IPv4, it are not leading slash.

### Steps to reproduce
1. insert data from vector to CH
2. view the data via CH JDBC driver

### Expected behaviour
No leading slash is added

### Code example
# See above

#### Environment
* Client version:
* Language version:
* OS: CH server in k3s server

#### ClickHouse server
* ClickHouse Server version: 22.8.15.23
* ClickHouse Server non-default settings, if any: Container under k3s
* `CREATE TABLE` statements for tables involved: see above
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
